services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./model:/app/model
      - ./templates:/app/templates
      - ./tokenize.pickle:/app/tokenize.pickle
